import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { generateAdapters } from "@intentloom/adapters";
import {
  INTENTLOOM_VERSION,
  type AdapterName,
  type Catalog,
} from "@intentloom/core";

interface SnapshotFixture {
  readonly name: string;
  readonly profile: string;
  readonly adapters: readonly AdapterName[];
  readonly expectedPaths?: readonly string[];
  readonly extends?: string;
  readonly additionalPaths?: readonly string[];
}

const fixtures = JSON.parse(
  readFileSync(resolve("tests/fixtures/adapters/snapshot-matrix.json"), "utf8"),
) as SnapshotFixture[];

const catalog: Catalog = {
  policies: ["policies/core.md", "policies/security.md"],
  workflows: ["workflows/delivery.md"],
  templates: [],
  skills: [
    {
      name: "plan",
      description: "Plan a bounded change.",
      sourcePath: "skills/plan/SKILL.md",
      content:
        "---\nname: plan\ndescription: Plan a bounded change.\n---\n\n# Plan\n",
    },
    {
      name: "review",
      description: "Review a bounded change.",
      sourcePath: "skills/review/SKILL.md",
      content:
        "---\nname: review\ndescription: Review a bounded change.\n---\n\n# Review\n",
    },
  ],
};

function expectedPaths(fixture: SnapshotFixture): readonly string[] {
  if (fixture.expectedPaths) return fixture.expectedPaths;
  const base = fixtures.find((candidate) => candidate.name === fixture.extends);
  if (!base?.expectedPaths) throw new Error(`invalid fixture: ${fixture.name}`);
  return [...base.expectedPaths, ...(fixture.additionalPaths ?? [])].sort(
    (left, right) => left.localeCompare(right),
  );
}

describe("committed adapter snapshot fixtures", () => {
  it.each(fixtures)("matches $name expected tree", (fixture) => {
    const first = generateAdapters(fixture.adapters, catalog, {
      profile: fixture.profile,
    });
    const second = generateAdapters([...fixture.adapters].reverse(), catalog, {
      profile: fixture.profile,
    });
    expect(second).toEqual(first);
    expect(first.files.map((file) => file.path)).toEqual(
      expectedPaths(fixture),
    );
    for (const file of first.files) {
      expect(file.path).not.toContain("\\");
      expect(file.path).not.toMatch(/^[A-Za-z]:|^\//u);
      expect(file.content).toContain(
        `Generated by Intentloom ${INTENTLOOM_VERSION}`,
      );
      expect(file.content).toContain(
        "Intentloom adapter output version: 0.1.0",
      );
      expect(file.content).not.toMatch(/\/Users\/|[A-Za-z]:\\/u);
      expect(file.content).not.toMatch(/20\d\d-\d\d-\d\d/u);
      expect(file.sources.every((source) => !source.startsWith("/"))).toBe(
        true,
      );
    }
  });
});
