import { describe, expect, it } from "vitest";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import {
  adoptProject,
  createMemoryFileSystem,
  type FileSystem,
} from "../packages/application/src/index.js";
import { runCli } from "../packages/cli/src/command.js";

function isPathWithin(root: string, candidate: string): boolean {
  const relativePath = relative(root, candidate);
  return (
    relativePath === "" ||
    (relativePath !== ".." &&
      !relativePath.startsWith(`..${sep}`) &&
      !isAbsolute(relativePath))
  );
}

describe("adoption proposal", () => {
  it.each([
    ["adopt", ["--dry-run"], 0, true],
    ["doctor", [], 3, true],
    ["diff", [], 0, true],
    ["sync", ["--dry-run"], 2, false],
  ] as const)(
    "%s accepts an explicit positional project path without writing",
    async (command, extra, expectedExit, expectsOutput) => {
      const projectRoot = resolve("explicit project");
      const fs = createMemoryFileSystem({
        [join(projectRoot, "README.md")]: "project\n",
      });
      const reads: string[] = [];
      const trackingFileSystem: FileSystem = {
        ...fs,
        exists: async (path) => {
          reads.push(path);
          return fs.exists(path);
        },
        read: async (path) => {
          reads.push(path);
          return fs.read(path);
        },
        list: async (path) => {
          reads.push(path);
          return fs.list(path);
        },
      };
      const before = [...fs.files.entries()];
      const stderr: string[] = [];
      const stdout: string[] = [];

      const exit = await runCli(
        [command, projectRoot, ...extra],
        { catalogRoot: resolve("catalog"), fileSystem: trackingFileSystem },
        {
          stdout: (message) => stdout.push(message),
          stderr: (message) => stderr.push(message),
        },
      );

      expect(exit).toBe(expectedExit);
      expect(stderr.join("\n")).not.toContain("unknown option");
      expect(stderr.join("\n")).not.toContain("unexpected argument");
      expect(stdout.join("\n") === "").toBe(!expectsOutput);
      expect(reads.some((path) => isPathWithin(projectRoot, path))).toBe(true);
      expect([...fs.files.entries()]).toEqual(before);
    },
  );

  it("rejects a positional project path combined with --root", async () => {
    const stderr: string[] = [];
    const exit = await runCli(
      ["doctor", "/first", "--root", "/second"],
      { catalogRoot: resolve("catalog"), fileSystem: createMemoryFileSystem() },
      { stdout: () => undefined, stderr: (message) => stderr.push(message) },
    );

    expect(exit).toBe(2);
    expect(stderr).toEqual(["project path specified more than once"]);
  });

  it("keeps existing instruction and documentation files project-owned", async () => {
    const initial = {
      "/project/AGENTS.md":
        "<!-- Generated by Intentloom 0.1.0; do not edit directly. -->\nprivate instructions\n",
      "/project/README.md": "public project readme\n",
      "/project/docs/architecture.md": "project architecture\n",
    };
    const fs = createMemoryFileSystem(initial);
    const options = {
      root: "/project",
      profile: "generic",
      adapters: ["codex"] as const,
      dryRun: true,
    };

    const first = await adoptProject(options, fs);
    const second = await adoptProject(options, fs);

    expect(first).toEqual(second);
    expect([...fs.files.entries()]).toEqual(Object.entries(initial));
    expect(first.items).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          path: "AGENTS.md",
          action: "map-existing-project-owned",
          currentClassification: "project-owned",
          proposedClassification: "project-owned",
          writeEligible: false,
          manualDecisionRequired: true,
        }),
        expect.objectContaining({
          path: "README.md",
          action: "map-existing-project-owned",
          proposedClassification: "project-owned-documentation",
          writeEligible: false,
        }),
        expect.objectContaining({
          path: "docs/architecture.md",
          action: "map-existing-aif-compatible-document",
          proposedClassification: "project-owned-documentation",
          writeEligible: false,
        }),
      ]),
    );
    expect(JSON.stringify(first)).not.toContain("private instructions");
  });

  it("reports malformed Intentloom ownership metadata as a blocking conflict", async () => {
    const fs = createMemoryFileSystem({
      "/project/.aif/source-map.json": "{ malformed",
    });
    const before = [...fs.files.entries()];
    const result = await adoptProject(
      {
        root: "/project",
        profile: "generic",
        adapters: ["codex"],
        dryRun: true,
      },
      fs,
    );
    expect(
      result.items.find((item) => item.path === ".aif/source-map.json")?.action,
    ).toBe("conflict");
    expect([...fs.files.entries()]).toEqual(before);
  });

  it("returns a proposal for corrupted metadata instead of failing before analysis", async () => {
    const fs = createMemoryFileSystem({
      "/project/.aif/config.yaml": "private-value: [",
    });
    const stdout: string[] = [];
    const stderr: string[] = [];
    const exitCode = await runCli(
      ["adopt", "--root", "/project", "--dry-run", "--json"],
      { catalogRoot: resolve("catalog"), fileSystem: fs },
      {
        stdout: (message) => stdout.push(message),
        stderr: (message) => stderr.push(message),
      },
    );
    const proposal = JSON.parse(stdout[0]!);
    expect(exitCode).toBe(3);
    expect(stderr).toEqual([]);
    expect(proposal.kind).toBe("adoption-proposal");
    expect(proposal.diagnostics).toContain(".aif/config.yaml: yaml-malformed");
    expect(stdout[0]).not.toContain("private-value");
  });
});
