import { describe, expect, it } from "vitest";
import { resolve } from "node:path";
import { adoptProject, createMemoryFileSystem } from "@aif/cli";
import { runCli } from "../packages/cli/src/command.js";

describe("adoption proposal", () => {
  it("keeps existing instruction and documentation files project-owned", async () => {
    const initial = {
      "/project/AGENTS.md":
        "<!-- Generated by AIF 0.1.0; do not edit directly. -->\nprivate instructions\n",
      "/project/README.md": "public project readme\n",
      "/project/docs/architecture.md": "project architecture\n",
    };
    const fs = createMemoryFileSystem(initial);
    const options = {
      root: "/project",
      profile: "generic",
      adapters: ["codex"] as const,
      dryRun: true,
    };

    const first = await adoptProject(options, fs);
    const second = await adoptProject(options, fs);

    expect(first).toEqual(second);
    expect([...fs.files.entries()]).toEqual(Object.entries(initial));
    expect(first.items).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          path: "AGENTS.md",
          action: "map-existing-project-owned",
          currentClassification: "project-owned",
          proposedClassification: "project-owned",
          writeEligible: false,
          manualDecisionRequired: true,
        }),
        expect.objectContaining({
          path: "README.md",
          action: "map-existing-project-owned",
          proposedClassification: "project-owned-documentation",
          writeEligible: false,
        }),
        expect.objectContaining({
          path: "docs/architecture.md",
          action: "map-existing-aif-compatible-document",
          proposedClassification: "project-owned-documentation",
          writeEligible: false,
        }),
      ]),
    );
    expect(JSON.stringify(first)).not.toContain("private instructions");
  });

  it("reports malformed AIF ownership metadata as a blocking conflict", async () => {
    const fs = createMemoryFileSystem({
      "/project/.aif/source-map.json": "{ malformed",
    });
    const before = [...fs.files.entries()];
    const result = await adoptProject(
      {
        root: "/project",
        profile: "generic",
        adapters: ["codex"],
        dryRun: true,
      },
      fs,
    );
    expect(
      result.items.find((item) => item.path === ".aif/source-map.json")?.action,
    ).toBe("conflict");
    expect([...fs.files.entries()]).toEqual(before);
  });

  it("returns a proposal for corrupted metadata instead of failing before analysis", async () => {
    const fs = createMemoryFileSystem({
      "/project/.aif/config.yaml": "private-value: [",
    });
    const stdout: string[] = [];
    const stderr: string[] = [];
    const exitCode = await runCli(
      ["adopt", "--root", "/project", "--dry-run", "--json"],
      { catalogRoot: resolve("catalog"), fileSystem: fs },
      {
        stdout: (message) => stdout.push(message),
        stderr: (message) => stderr.push(message),
      },
    );
    const proposal = JSON.parse(stdout[0]!);
    expect(exitCode).toBe(3);
    expect(stderr).toEqual([]);
    expect(proposal.kind).toBe("adoption-proposal");
    expect(proposal.diagnostics).toContain(".aif/config.yaml: yaml-malformed");
    expect(stdout[0]).not.toContain("private-value");
  });
});
