import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { resolve, sep } from "node:path";
import { parse as parseYaml } from "yaml";

import { AIF_VERSION } from "./version.js";
export { AIF_VERSION };

export type AdapterName = "claude" | "codex" | "cursor" | "copilot";

export interface Skill {
  readonly name: string;
  readonly description: string;
  readonly sourcePath: string;
  readonly content: string;
}

export interface Catalog {
  readonly policies: readonly string[];
  readonly workflows: readonly string[];
  readonly templates: readonly string[];
  readonly skills: readonly Skill[];
}

export interface GeneratedFile {
  readonly path: string;
  readonly content: string;
  readonly sources: readonly string[];
  readonly checksum: string;
}

export interface AifConfig {
  readonly schemaVersion: "1";
  readonly profile: string;
  readonly adapters: readonly AdapterName[];
}

export function checksum(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex");
}

export function normalizeStoredPath(candidate: string): string {
  const invalid = () => {
    throw new Error("stored path must be safe and project-relative");
  };
  if (
    candidate === "" ||
    candidate.includes("\0") ||
    /^[A-Za-z]:/u.test(candidate) ||
    candidate.startsWith("/") ||
    candidate.startsWith("\\")
  )
    return invalid();
  const segments: string[] = [];
  for (const rawSegment of candidate.replaceAll("\\", "/").split("/")) {
    if (rawSegment === "" || rawSegment === ".") continue;
    if (rawSegment === "..") return invalid();
    const segment = rawSegment.normalize("NFC");
    const device = segment.split(".", 1)[0]!.toUpperCase();
    if (
      /[<>:"|?*\u0000-\u001f]/u.test(segment) ||
      /[ .]$/u.test(segment) ||
      /^(?:CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])$/u.test(device)
    )
      return invalid();
    segments.push(segment);
  }
  if (segments.length === 0) return invalid();
  return segments.join("/");
}

export function storedPathCollisionKey(candidate: string): string {
  if (
    candidate === "" ||
    /^[A-Za-z]:/u.test(candidate) ||
    candidate.startsWith("/") ||
    candidate.startsWith("\\")
  )
    throw new Error("stored path must be safe and project-relative");
  const segments: string[] = [];
  for (const segment of candidate.replaceAll("\\", "/").split("/")) {
    if (segment === "" || segment === ".") continue;
    if (segment === "..") {
      if (segments.length === 0)
        throw new Error("stored path must be safe and project-relative");
      segments.pop();
    } else segments.push(segment);
  }
  return normalizeStoredPath(segments.join("/")).toLowerCase();
}

export function normalizeOutputPath(candidate: string): string {
  try {
    return normalizeStoredPath(candidate);
  } catch {
    if (candidate.replaceAll("\\", "/").split("/").includes(".."))
      throw new Error(`output path escapes the project root: ${candidate}`);
    throw new Error(`output path must be project-relative: ${candidate}`);
  }
}

export function resolveWithin(root: string, candidate: string): string {
  const absoluteRoot = resolve(root);
  const target = resolve(absoluteRoot, candidate);
  if (target !== absoluteRoot && !target.startsWith(`${absoluteRoot}${sep}`)) {
    throw new Error(`path escapes the supplied root: ${candidate}`);
  }
  return target;
}

export function generatedHeader(
  sourcePaths: readonly string[],
  body: string,
  comment = "#",
): string {
  const digest = checksum(body);
  return [
    `${comment} Generated by AIF ${AIF_VERSION}; do not edit manually.`,
    `${comment} Canonical source: ${sourcePaths.join(", ")}`,
    `${comment} Content checksum: sha256:${digest}`,
    "",
  ].join("\n");
}

export function generatedFile(
  path: string,
  body: string,
  sources: readonly string[],
  comment = "#",
): GeneratedFile {
  const normalizedPath = normalizeOutputPath(path);
  const content = `${generatedHeader(sources, body, comment)}${body}`;
  return {
    path: normalizedPath,
    content,
    sources,
    checksum: checksum(content),
  };
}

export function parseSkill(sourcePath: string, content: string): Skill {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/u.exec(content);
  if (!match) throw new Error(`${sourcePath}: missing YAML frontmatter`);
  // The full-match guard above guarantees the first capture exists.
  const frontmatter = parseYaml(match[1]!) as unknown;
  if (typeof frontmatter !== "object" || frontmatter === null)
    throw new Error(`${sourcePath}: invalid frontmatter`);
  const fields = frontmatter as Record<string, unknown>;
  if (
    typeof fields.name !== "string" ||
    !/^[a-z0-9-]{1,64}$/u.test(fields.name)
  ) {
    throw new Error(`${sourcePath}: invalid skill name`);
  }
  if (
    typeof fields.description !== "string" ||
    fields.description.trim() === ""
  ) {
    throw new Error(`${sourcePath}: missing skill description`);
  }
  return {
    name: fields.name,
    description: fields.description,
    sourcePath,
    content,
  };
}

async function markdownFiles(
  root: string,
  directory: string,
): Promise<string[]> {
  const absolute = resolveWithin(root, directory);
  const entries = await readdir(absolute, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => `${directory}/${entry.name}`)
    .sort();
}

export async function loadCatalog(catalogRoot: string): Promise<Catalog> {
  const policies = await markdownFiles(catalogRoot, "policies");
  const workflows = await markdownFiles(catalogRoot, "workflows");
  const templates = await markdownFiles(catalogRoot, "templates");
  const skillDirectories = (
    await readdir(resolveWithin(catalogRoot, "skills"), { withFileTypes: true })
  )
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const skills = await Promise.all(
    skillDirectories.map(async (directory) => {
      const sourcePath = `skills/${directory}/SKILL.md`;
      return parseSkill(
        sourcePath,
        await readFile(resolveWithin(catalogRoot, sourcePath), "utf8"),
      );
    }),
  );
  return { policies, workflows, templates, skills };
}

export function parseAifConfig(value: string): AifConfig {
  const parsed = parseYaml(value) as unknown;
  if (typeof parsed !== "object" || parsed === null)
    throw new Error("config must be an object");
  const config = parsed as Record<string, unknown>;
  if (
    config.schemaVersion !== "1" ||
    typeof config.profile !== "string" ||
    !Array.isArray(config.adapters)
  ) {
    throw new Error("config does not satisfy AIF schema version 1");
  }
  const adapters = config.adapters;
  if (
    !adapters.every(
      (adapter) =>
        adapter === "claude" ||
        adapter === "codex" ||
        adapter === "cursor" ||
        adapter === "copilot",
    )
  ) {
    throw new Error("config contains an unsupported adapter");
  }
  return { schemaVersion: "1", profile: config.profile, adapters };
}
