import { readFile, rename, writeFile } from "node:fs/promises";

async function writeAtomic(file, content) {
  const temporary = `${file}.${process.pid}.tmp`;
  await writeFile(temporary, content);
  await rename(temporary, file);
}

const root = JSON.parse(await readFile("package.json", "utf8"));
const packageFiles = [
  "packages/core/package.json",
  "packages/application/package.json",
  "packages/adapters/package.json",
  "packages/validator/package.json",
  "packages/cli/package.json",
  "packages/protocol/package.json",
  "packages/daemon/package.json",
  "packages/evidence-git/package.json",
  "packages/evidence-provider/package.json",
  "packages/evidence-analysis/package.json",
  "packages/mcp-server/package.json",
];
for (const file of packageFiles) {
  const value = JSON.parse(await readFile(file, "utf8"));
  value.version = root.version;
  await writeAtomic(file, `${JSON.stringify(value, null, 2)}\n`);
}
await writeAtomic(
  "packages/core/src/version.ts",
  `// Generated by scripts/sync-version.mjs from the root package.json.\nexport const INTENTLOOM_VERSION = ${JSON.stringify(root.version)};\n`,
);
