import { readFile, writeFile } from "node:fs/promises";

const root = JSON.parse(await readFile("package.json", "utf8"));
const packageFiles = ["packages/core/package.json", "packages/adapters/package.json", "packages/validator/package.json", "packages/cli/package.json"];
for (const file of packageFiles) { const value = JSON.parse(await readFile(file, "utf8")); value.version = root.version; await writeFile(file, `${JSON.stringify(value, null, 2)}\n`); }
await writeFile("packages/core/src/version.ts", `// Generated by scripts/sync-version.mjs from the root package.json.\nexport const INTENTLOOM_VERSION = ${JSON.stringify(root.version)};\n`);
