import {
  type AdapterName,
  checksum,
  type Catalog,
  generatedFile,
  generatedHeader,
  type GeneratedFile,
  normalizeOutputPath,
} from "@aif/core";

export interface AdapterResult {
  readonly adapter: AdapterName;
  readonly files: readonly GeneratedFile[];
  readonly unsupported: readonly string[];
}

const adapterVersion = "0.1.0";

function sharedInstructions(catalog: Catalog): string {
  return [
    "# AIF project guidance",
    "",
    "Follow the generated AIF policies and use focused skills for task-specific workflows.",
    "Do not edit generated files manually; update the canonical catalog and regenerate.",
    "",
    "## Canonical policy sources",
    ...catalog.policies.map((source) => `- ${source}`),
    "",
  ].join("\n");
}

function skillFiles(catalog: Catalog, directory: string): GeneratedFile[] {
  return catalog.skills.map((skill) => {
    const marker = "---\n";
    const end = skill.content.indexOf(marker, marker.length);
    if (!skill.content.startsWith(marker) || end < 0)
      throw new Error(`invalid canonical skill: ${skill.sourcePath}`);
    const frontmatter = skill.content.slice(0, end + marker.length);
    const instructions = skill.content.slice(end + marker.length);
    const content = `${frontmatter}\n${generatedHeader([skill.sourcePath], instructions)}${instructions}`;
    const path = normalizeOutputPath(`${directory}/${skill.name}/SKILL.md`);
    return {
      path,
      content,
      sources: [skill.sourcePath],
      checksum: checksum(content),
    };
  });
}

export function generateAdapter(
  adapter: AdapterName,
  catalog: Catalog,
): AdapterResult {
  const common = sharedInstructions(catalog);
  switch (adapter) {
    case "claude":
      return {
        adapter,
        files: [
          generatedFile("AGENTS.md", common, catalog.policies),
          generatedFile("CLAUDE.md", "@AGENTS.md\n", ["AGENTS.md"]),
          ...skillFiles(catalog, ".claude/skills"),
        ],
        unsupported: ["hooks and permissions are intentionally not generated"],
      };
    case "codex":
      return {
        adapter,
        files: [
          generatedFile("AGENTS.md", common, catalog.policies),
          ...skillFiles(catalog, ".agents/skills"),
        ],
        unsupported: [".codex/config.toml is intentionally not generated"],
      };
    case "cursor":
      return {
        adapter,
        files: [
          generatedFile("AGENTS.md", common, catalog.policies),
          generatedFile(
            ".cursor/rules/aif-core.mdc",
            `---\ndescription: AIF shared project guidance\nalwaysApply: true\n---\n\n${common}`,
            catalog.policies,
          ),
          ...skillFiles(catalog, ".agents/skills"),
        ],
        unsupported: [
          ".cursorignore is profile-optional and not generated by the generic adapter",
          "legacy .cursorrules is unsupported",
        ],
      };
    case "copilot":
      return {
        adapter,
        files: [
          generatedFile("AGENTS.md", common, catalog.policies),
          generatedFile(
            ".github/copilot-instructions.md",
            common,
            catalog.policies,
          ),
          generatedFile(
            ".github/instructions/aif.instructions.md",
            `---\napplyTo: \"**\"\n---\n\n${common}`,
            catalog.policies,
          ),
          ...skillFiles(catalog, ".github/skills"),
        ],
        unsupported: [
          "custom agents are not generated because support differs by Copilot environment",
        ],
      };
  }
}

export function generateAllAdapters(
  catalog: Catalog,
): readonly AdapterResult[] {
  return (["claude", "codex", "cursor", "copilot"] as const).map((adapter) =>
    generateAdapter(adapter, catalog),
  );
}

export { adapterVersion };
